version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    build: .
    container_name: gym_backend
    ports:
      - "7151:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__GymDBConnection=Server=db;Database=GymDB;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mssql_data:
